name: Build and push Image Docker

on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]

jobs:
  build:
    runs-on: mac

steps:
- uses: actions/checkout@v1

-name: Docker Login
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
run:  |
  docker login - $DOCKER_USER -p $DOCKER_PASSWORD

